name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "sqlite::memory:"

    steps:
    - uses: actions/checkout@v3
    - name: Install Diesel CLI
      run: cargo install diesel_cli --no-default-features --features sqlite
    - name: Run Diesel Migrations
      run: diesel migration run
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Lint with clippy
      run: cargo clippy -- -D warnings
